---
apiVersion: v1
kind: ConfigMap
metadata:
  name: config
data:
  dbUrl: "postgresql://staging.example.pvt:5432"
  foo: bar
---
apiVersion: v1
kind: Secret
metadata:
  name: creds
data:
  user: YWRtaW4= # admin
  password: ZGV2b3BzMTIz # devops123
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
        - name: myapp
          image: nginx:1.14.2
          ports:
            - name: http
              containerPort: 8080
          env:
            - name: MY_USERNAME
              valueFrom:
                secretKeyRef:
                  name: creds
                  key: user
            - name: MY_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: creds
                  key: password
          volumeMounts:
            - name: config
              mountPath: /etc/config
      volumes:
        - name: config
          configMap:
            name: config
