apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapRoles: |
    - rolearn: arn:aws:iam::123456789012:role/K8sAdminRole
      username: admin
      groups:
        - system:masters
    - rolearn: arn:aws:iam::123456789012:role/K8sReadOnlyRole
      username: readonly
      groups:
        - system:view
  mapUsers: |
    - userarn: arn:aws:iam::123456789012:user/JohnDoe
      username: john
      groups:
        - system:masters
    - userarn: arn:aws:iam::123456789012:user/JaneDoe
      username: jane
      groups:
        - system:view